version: '3.8'

services:
  frontend1:
    build: .
    container_name: nextjs-frontend1
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  frontend2:
    build: .
    container_name: nextjs-frontend2
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
